input {
     file {
      path => "/home/hdu/datasets/Bank_full.csv"
      start_position => "beginning"
      sincedb_path => "/dev/null"
      }
}
filter {
     csv {
         separator => ","
         columns => ["serNo","age","job","marital","education","default","balance","housing","loan","contact","day","month","duration","campaign","pdays","previous","poutcome","y"]
     }
     mutate {convert => ["age","integer"]}
     mutate {convert => ["balance","float"]}
     mutate {convert => ["duration","integer"]}

}

output {
  elasticsearch {
    hosts => [
      "https://localhost:9200",
      "https://localhost:9201",
      "https://localhost:9202"
    ]

    user => "elastic"
    password => "9_W6d34GiGU8gKoZfLlO"

    ssl_enabled => true
    ssl_certificate_authorities => ["/home/hdu/elasticsearch/config/certs/http_ca.crt"]

    index => "bankdata2"
  }

  stdout {}
}

