input {

  exec {
    command => "find /home/hdu/datasets/pdfs -name '*.pdf'"
    interval => 3600
  }

}

filter {

  split {
    field => "message"
  }

  mutate {
    rename => {
      "message" => "path"
    }
  }

  ruby {
    code => '
      require "base64"

      path = event.get("path").strip

      pdf_data = File.binread(path)

      encoded = Base64.strict_encode64(pdf_data)

      event.set("data", encoded)
    '
  }

  mutate {
    add_field => {
      "filename" => "%{path}"
    }
  }

}

output {

  elasticsearch {

    hosts => [
      "https://localhost:9200",
      "https://localhost:9201",
      "https://localhost:9202"
    ]

    user => "elastic"

    password => "9_W6d34GiGU8gKoZfLlO"

    ssl_enabled => true

    ssl_certificate_authorities => [
      "/home/hdu/elasticsearch/config/certs/http_ca.crt"
    ]

    index => "pdf-index"

    pipeline => "pdf-pipeline"
  }

  stdout {
    codec => rubydebug
  }

}